" Toggle Menu and Toolbar
set guioptions-=m
set guioptions-=T
set guioptions-=l
set guioptions-=r

set guifont=IBM\ Plex\ Mono\ 16

let $PATH = '/home/riczzoe/.miniforge/bin:' . $PATH
source ~/.vimrc
